### ISSUE TITLE
Problem nach Raspberry-Update. Was ist hier passiert?

### ISSUE THREAD

**Issue by steviean** [hhoefling/citigo#2]
pi@raspberrypi:/var/www/html/lp1 $ ./soc_citigo/getsoc.sh
callskoda.py for LP1 debug:1
Init Skoda Connect library, version 1.3.2
Initiating new session to Skoda Connect with ***@*** as username
Attempting to login to the Skoda Connect service
2023-01-10 17:27:42.532004
Login success!
2023-01-10 17:27:54.315315
Fetching vehicles associated with account.
Traceback (most recent call last):
  File "/var/www/html/lp1/soc_citigo/callskoda.py", line 309, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/var/www/html/lp1/soc_citigo/callskoda.py", line 205, in main
    typ = type(eval(func))
  File "<string>", line 1, in <module>
  File "/var/www/html/lp1/soc_citigo/skodaconnect/vehicle.py", line 2290, in aux_heater_for_departure
    if self.departure1.get('heaterSource', 'electric') == 'automatic':
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by hhoefling** [comment]
Hm. Keine Ahnung, was wurde den "upgedatet"?

**Comment by hhoefling** [comment]
Ich musste Heute mal wieder mit dem Handy irgendeinen Zugriff  zustimmen.
Ansonsten gehts hier.

**Comment by steviean** [comment]
> Hm. Keine Ahnung, was wurde den "upgedatet"?

Node Red wurde upgedated und da hat er noch einige andere Pakete erneuert.

Ich hab es leider nicht mehr zum Laufen gebracht, so dass nichts anderes übrig blieb, als ein Backupimage auf die SD zu ziehen - nun läuft es wieder.

Danke :-)
